import Orders from "./components/Orders";
import TableList from "./components/TableList";
import Plates from "./components/Plates";
import WaitersList from "./components/WaitersList";
import UpdateOrderButton from "./components/UpdateOrderButton";
import PrenTableButton from "./components/PrenTableButton";
import OrderInput from "./components/OrderInput";
import CreateUser from "./components/CreateUser";
import SignUpButton from "./components/SignUpButton";
