# Generated by Django 2.2 on 2020-07-09 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='table_mgmt.Person')),
                ('psw', models.CharField(max_length=32)),
            ],
            bases=('table_mgmt.person',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='table_mgmt.Person')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
            bases=('table_mgmt.person',),
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='table_mgmt.Person')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
            bases=('table_mgmt.person',),
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('available', models.BooleanField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_mgmt.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Client_Auth',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='table_mgmt.Client')),
                ('e_mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Clients_Auth',
            },
            bases=('table_mgmt.client',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('t_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_mgmt.Table')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_mgmt.Waiter')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_mgmt.Order'),
        ),
    ]
