# Generated by Django 2.2 on 2020-07-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
