# Generated by Django 2.2 on 2020-07-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='table_mgmt.Person')),
                ('name', models.CharField(max_length=50)),
                ('surnam', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('table_mgmt.person',),
        ),
    ]
