# Generated by Django 2.2 on 2020-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plates',
            field=models.ManyToManyField(to='table_mgmt.Plate'),
        ),
    ]
