# Generated by Django 2.2 on 2020-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plate',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plate',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plate',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plate',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plate',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plate',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
