# Generated by Django 2.2 on 2020-08-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seats',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
