# Generated by Django 2.2 on 2020-07-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0002_auto_20200709_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='day',
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='Foo description', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(),
        ),
    ]
