# Generated by Django 2.2 on 2020-08-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0002_order_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='password',
            field=models.IntegerField(),
        ),
    ]
