# Generated by Django 2.2 on 2020-07-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0002_order_plates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
