# Generated by Django 2.2 on 2020-07-07 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0002_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='surnam',
            new_name='surname',
        ),
    ]
