# Generated by Django 2.2 on 2020-08-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0003_auto_20200824_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='password',
            field=models.TextField(),
        ),
    ]
