# Generated by Django 2.2 on 2020-08-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0004_auto_20200824_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
