# Generated by Django 2.2 on 2020-07-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0004_auto_20200707_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='table',
        ),
    ]
