# Generated by Django 2.2 on 2020-08-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0005_auto_20200824_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
