# Generated by Django 2.2 on 2020-07-07 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0005_remove_person_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='table_mgmt.Table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
