# Generated by Django 2.2 on 2020-08-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0006_plate_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='quantity',
        ),
    ]
