# Generated by Django 2.2 on 2020-08-26 09:53

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0007_remove_plate_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plates_quantity',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
            preserve_default=False,
        ),
    ]
