# Generated by Django 2.2 on 2020-08-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_mgmt', '0008_order_plates_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plates_quantity',
        ),
    ]
